- name: vreasoner
  _target_: verl.experimental.agent_loop.insight_o3_agent_loop.VReasonerLoop
  model: gemini-2.5-flash
  max_tool_calls: 6
  max_round_retries: 3
  gpt_image_max_area: 12250000  # 3500*3500
  max_completion_tokens: 2048
  reasoning_effort: null
  enable_tool_feedback: True    # whether provide feedback to vsearcher during training;
                                # during validation, feedback is always disabled, ignoring this setting
- name: vsearcher
  _target_: verl.experimental.agent_loop.insight_o3_agent_loop.VSearcherLoop