- name: qwen_agent
  _target_: verl.experimental.agent_loop.qwen_agent_loop.QwenAgentLoop

- name: insight_qwen_agent
  _target_: verl.experimental.agent_loop.qwen_agent_loop.InSightQwenAgentLoop
  presented_initial_rescale: 0.25
  presented_max_area: 1638400
  region_zoom_in_factor: 4.0
