- name: vreasoner_v2
  _target_: verl.experimental.agent_loop.insight_o3_agent_loop.VReasonerLoopV2
  model: gemini-3-flash-preview
  max_tool_calls: 6
  max_round_retries: 3
  max_round_retries_val: 5
  gpt_image_max_area: 1638400
  max_completion_tokens: 8192
  region_zoom_in_factor: 3.0
  reasoning_effort: null
  multi_image_input: True
  enable_stop: True
- name: vsearcher
  _target_: verl.experimental.agent_loop.insight_o3_agent_loop.VSearcherLoop