- name: vreasoner
  _target_: verl.experimental.agent_loop.insight_o3_agent_loop.VReasonerLoop
  model: gemini-3-flash-preview
  max_tool_calls: 10
  max_round_retries: 3
  max_round_retries_val: 5      # more permissive for validation
  gpt_image_max_area: 1638400   # 1280*1280
  max_completion_tokens: 8192
  reasoning_effort: null
  enable_tool_feedback: True    # whether provide feedback to vsearcher during training;
                                # during validation, feedback is always disabled, ignoring this setting
  multi_image_input: True
- name: vsearcher
  _target_: verl.experimental.agent_loop.insight_o3_agent_loop.VSearcherLoop