weights:
  arxiv_veqa_answerable_r025: 0.104125
  arxiv_veqa_answerable_r035: 0.02975
  arxiv_veqa_answerable_r05: 0.014875
  arxiv_veqa_unanswerable_r025: 0.018375
  arxiv_veqa_unanswerable_r035: 0.00525
  arxiv_veqa_unanswerable_r05: 0.002625
  arxiv_mveqa_answerable_r025: 0.104125
  arxiv_mveqa_answerable_r035: 0.02975
  arxiv_mveqa_answerable_r05: 0.014875
  arxiv_mveqa_unanswerable_r025: 0.018375
  arxiv_mveqa_unanswerable_r035: 0.00525
  arxiv_mveqa_unanswerable_r05: 0.002625
  map_metro_answerable_r025: 0.08925
  map_metro_answerable_r035: 0.0255
  map_metro_answerable_r05: 0.01275
  map_metro_unanswerable_r025: 0.01575
  map_metro_unanswerable_r035: 0.0045
  map_metro_unanswerable_r05: 0.00225
  map_travel_answerable_r025: 0.02975
  map_travel_answerable_r035: 0.0085
  map_travel_answerable_r05: 0.00425
  map_travel_unanswerable_r025: 0.00525
  map_travel_unanswerable_r035: 0.0015
  map_travel_unanswerable_r05: 0.00075
  docvqa_answerable_r025: 0.0595
  docvqa_answerable_r035: 0.017
  docvqa_answerable_r05: 0.0085
  docvqa_unanswerable_r025: 0.0105
  docvqa_unanswerable_r035: 0.003
  docvqa_unanswerable_r05: 0.0015
  dude_answerable_r025: 0.119
  dude_answerable_r035: 0.034
  dude_answerable_r05: 0.017
  dude_unanswerable_r025: 0.021
  dude_unanswerable_r035: 0.006
  dude_unanswerable_r05: 0.003
  poster_answerable_r025: 0.0595
  poster_answerable_r035: 0.017
  poster_answerable_r05: 0.0085
  poster_unanswerable_r025: 0.0105
  poster_unanswerable_r035: 0.003
  poster_unanswerable_r05: 0.0015
  info_answerable_r025: 0.02975
  info_answerable_r035: 0.0085
  info_answerable_r05: 0.00425
  info_unanswerable_r025: 0.00525
  info_unanswerable_r035: 0.0015
  info_unanswerable_r05: 0.00075
